# Form implementation generated from reading ui file 'd:\Kuliah\Semester 6\Pemvis\Tugas-Pemvis\pv25-finalProject\ui\dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashboardWidget(object):
    def setupUi(self, DashboardWidget):
        DashboardWidget.setObjectName("DashboardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(DashboardWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=DashboardWidget)
        self.titleLabel.setStyleSheet("font-size: 20px; font-weight: bold;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.historyTable = QtWidgets.QTableWidget(parent=DashboardWidget)
        self.historyTable.setMinimumHeight(300)
        self.historyTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.historyTable.setObjectName("historyTable")
        self.historyTable.setColumnCount(0)
        self.historyTable.setRowCount(0)
        self.verticalLayout.addWidget(self.historyTable)
        self.predictButton = QtWidgets.QPushButton(parent=DashboardWidget)
        self.predictButton.setStyleSheet("\n"
"        padding: 10px;\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        border-radius: 5px;\n"
"      ")
        self.predictButton.setObjectName("predictButton")
        self.verticalLayout.addWidget(self.predictButton)

        self.retranslateUi(DashboardWidget)
        QtCore.QMetaObject.connectSlotsByName(DashboardWidget)

    def retranslateUi(self, DashboardWidget):
        _translate = QtCore.QCoreApplication.translate
        DashboardWidget.setWindowTitle(_translate("DashboardWidget", "Dashboard"))
        self.titleLabel.setText(_translate("DashboardWidget", "Riwayat Prediksi Penyakit Kulit"))
        self.historyTable.setSortingEnabled(True)
        self.predictButton.setText(_translate("DashboardWidget", "🩺 Lakukan Prediksi Baru"))
