# Form implementation generated from reading ui file 'd:\Kuliah\Semester 6\Pemvis\Tugas-Pemvis\pv25-finalProject\ui\login_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(400, 400)
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(LoginWidget)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainVerticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout = QtWidgets.QVBoxLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.logoLabel = QtWidgets.QLabel(parent=LoginWidget)
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.logoLabel.setObjectName("logoLabel")
        self.formLayout.addWidget(self.logoLabel)
        self.titleLabel = QtWidgets.QLabel(parent=LoginWidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setStyleSheet("font-size: 18px; font-weight: bold; margin-bottom: 10px;")
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.addWidget(self.titleLabel)
        self.emailInput = QtWidgets.QLineEdit(parent=LoginWidget)
        self.emailInput.setStyleSheet("\n"
"            QLineEdit {\n"
"              padding: 8px;\n"
"              font-size: 14px;\n"
"              border: 1px solid #ccc;\n"
"              border-radius: 5px;\n"
"            }\n"
"          ")
        self.emailInput.setObjectName("emailInput")
        self.formLayout.addWidget(self.emailInput)
        self.passwordInput = QtWidgets.QLineEdit(parent=LoginWidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setStyleSheet("\n"
"            QLineEdit {\n"
"              padding: 8px;\n"
"              font-size: 14px;\n"
"              border: 1px solid #ccc;\n"
"              border-radius: 5px;\n"
"            }\n"
"          ")
        self.passwordInput.setObjectName("passwordInput")
        self.formLayout.addWidget(self.passwordInput)
        self.loginButton = QtWidgets.QPushButton(parent=LoginWidget)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginButton.setStyleSheet("\n"
"            QPushButton {\n"
"              background-color: #2e86de;\n"
"              color: white;\n"
"              padding: 10px;\n"
"              font-weight: bold;\n"
"              border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"              background-color: #1b4f72;\n"
"            }\n"
"          ")
        self.loginButton.setObjectName("loginButton")
        self.formLayout.addWidget(self.loginButton)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.mainVerticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainVerticalLayout.addItem(spacerItem3)

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("LoginWidget", "Login ke SadarKulit"))
        self.emailInput.setPlaceholderText(_translate("LoginWidget", "Masukkan email Anda"))
        self.passwordInput.setPlaceholderText(_translate("LoginWidget", "Masukkan password"))
        self.loginButton.setText(_translate("LoginWidget", "Login"))
